### ISSUE TITLE
Register Email Reply

### ISSUE THREAD

**Issue by ddbrand** [ddbrand/ddapp-v1#7]
Statt 
![Screen Shot 2019-04-02 at 14 43 37](https://user-images.githubusercontent.com/47419456/55403321-df648a00-5555-11e9-9af0-d4ab750fa594.png)
 Bitte so:
![Screen Shot 2019-04-02 at 15 11 35](https://user-images.githubusercontent.com/47419456/55405123-ad552700-5559-11e9-87ee-69c33a176010.png)

Text für dich zum Kopieren :)
Welcome to DD

You have created a DD Training ID with the username: April 

Please confirm your email address

Confirm

(This link will expire in 4 hours.)

powered by #ddrobotec

**Comment by RenewedPlains** [comment]
Sämtliche Mails werden durch die Cloud generiert. Gecoded wurde dies von Max/Emilio. Ich kann das Aussehen nicht verändern, dass müssten sie tun.
